- src/services/index.ts
- src/store/modules/helpers.ts
- src/views/AddModule/modals/ExitModuleModal.tsx
Allow the user to enter a circulating supply contract address or enter the circulating supply amount to deploy a new Circulating Supply Contract.
The process of deploying a new contract is:
- Enter the Circulating Supply amount
- Use CREATE2 to calculate the expected contract address.
- The Circulating Supply contract is deploy using the ModuleFactory contract (same way as deploying a module)
- Deploy the Exit module with the Token Address (entered by user) and the Circulating Supply expected address.
- Enable Exit Module transaction.
| Deploy New Contract | Enter Address |
| - | - |
| ![Screenshot from 2021-09-02 02-41-23](https://user-images.githubusercontent.com/2939980/131795217-7459455e-2f0a-49ba-9957-6f1ab58b941d.png) | ![Screenshot from 2021-09-02 …
> Exit Module - Deploy Circulating Supply Contract

- src/index.tsx
This was causing an invalid CSS property, my bad 😶
> Add in missing parenthesis

- package.json
- yarn.lock
Update Zodiac v1.0.2. this includes:
- contract addresses using singleton factory
- contract addresses deployed on xDai and Polygon
> feat: update zodiac to v1.0.2

- package.json
- src/components/input/ArbitratorSelect.tsx
- src/services/index.ts
- src/utils/explorers.ts
- src/utils/networks.ts
- src/utils/reality-eth.ts
- src/views/AddModule/modals/RealityModuleModal.tsx
- yarn.lock
> [FIXES] Minimum Bond & Display Native asset 

- src/services/helpers.ts
- src/services/index.ts
- src/store/modules/helpers.ts
- src/utils/contracts.ts
- src/utils/explorers.ts
- src/utils/modulesValidation.ts
Avoid using a default provider for some actions
> Avoid using a default provider for some actions

- src/store/modules/helpers.ts
While testing the Roles Mod when found a recursion issue with the app, if a module is a sub-module of a sub-module (recursive call), an infinity loop is created.
A list of the previous modules fetched is stored, if a sub-module is found in this list, its execution is skipped.
> [fix] Avoid infinity recursion if a sub-module is recursive

- package.json
- yarn.lock
Bumps to the latest Zodiac version.
> bump zodiac version

- src/components/circleStep/CircleStep.tsx
- src/views/RealityModule/RealityModule.tsx
- src/views/RealityModule/sections/monitoring/MonitoringSection.tsx
- src/views/RealityModule/sections/oracle/OracleSection.tsx
- src/views/RealityModule/sections/oracle/components/oracleArbitration/OracleArbitration.tsx
- src/views/RealityModule/sections/oracle/components/oracleDelay/OracleDelay.tsx
- src/views/RealityModule/sections/oracle/components/oracleInstance/OracleInstance.tsx
- src/views/RealityModule/sections/proposal/ProposalSection.tsx
- src/views/RealityModule/sections/review/ReviewSection.tsx
- yarn.lock
closed #69 
closed #70 
Monitoring UI
Review UI
> Create Monitoring and Review section UI

- src/components/Alert/DangerAlert.tsx
- src/components/circleStep/CircleStep.tsx
- src/components/input/TimeSelect.tsx
- src/utils/ens.ts
- src/views/RealityModule/RealityModule.tsx
- src/views/RealityModule/sections/oracle/OracleSection.tsx
- src/views/RealityModule/sections/oracle/components/oracleArbitration/OracleArbitration.tsx
- src/views/RealityModule/sections/oracle/components/oracleDelay/OracleDelay.tsx
- src/views/RealityModule/sections/oracle/components/oracleInstance/OracleInstance.tsx
- src/views/RealityModule/sections/oracle/components/oracleTemplate/OracleTemplate.tsx
- src/views/RealityModule/sections/proposal/ProposalSection.tsx
- src/views/RealityModule/sections/proposal/components/proposalStatus/ProposalStatus.tsx
- src/views/RealityModule/sections/review/ReviewSection.tsx
> Add validation and improve the UX

- package.json
- yarn.lock
This PR updates to the latest Zodiac version.
> update zodiac version and bump package version

- src/store/modules/constants.ts
Adding all chains with Gnosis Safe + Zodiac support
> Add all support chains

- packages/app/src/components/input/TimeSelect.tsx
- packages/app/src/hooks/useKeyPress.ts
closed #101 
This PR contains an improvement for TimeSelect Dropdown; from now on, we can close the menu by using the tab button.
> [Reality Module] - keyboard improvements

- packages/app/src/views/AddModule/wizards/RealityModule/service/minitoring.ts
Prevent "empty" requests our monitoring API
> [Reality Module] Prevent "empty" requests our monitoring API

- packages/app/src/utils/safeAppLink.ts
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Proposal/index.tsx
- packages/app/src/views/Panel/item/RoleModuleItem.tsx
Fix linking from Safe app to Safe app
> Fix safe app links

- packages/app/src/hooks/usePrevious.ts
- packages/app/src/views/AddModule/wizards/RealityModule/hooks/useMonitoringValidation.ts
- packages/app/src/views/AddModule/wizards/RealityModule/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Monitoring/components/MonitoringStatus/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Monitoring/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Review/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/service/monitoring.ts
- packages/app/src/views/AddModule/wizards/RealityModule/service/setupService.ts
- packages/backend/api/monitoring/types.ts
- packages/backend/api/monitoring/validation.ts
- packages/backend/package.json
- packages/backend/yarn.lock
Closed #118 
This PR contains the following improvements:
UI:
> [Reality Module] -  Validate Monitoring Fields

- packages/app/src/views/AddModule/wizards/RealityModule/sections/Oracle/components/OracleTemplate/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Oracle/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Review/index.tsx
- Make the default template question the initial value.
- Use the actual template question, instead of the hardcoded variant.
> Various template question fixes

- packages/app/src/views/AddModule/wizards/RealityModule/sections/Oracle/components/OracleInstance/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Oracle/index.tsx
> Update testnet address

- packages/app/src/views/AddModule/wizards/RealityModule/sections/Oracle/components/OracleTemplate/index.tsx
> [Reality Module] Clarify how the template works

- packages/app/src/views/AddModule/index.tsx
- packages/app/src/views/AddModule/wizards/ModalWizards.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/service/moduleDeployment.ts
- packages/app/src/views/AddModule/wizards/RealityModuleOld/RealityModuleOldModal.tsx
- packages/app/src/views/AddModule/wizards/RealityModuleOld/services/moduleDeploymentOld.ts
Enable the old Reality Module wizard for chains other than Goerli and Mainnet.
Fixes #136
> Enable the old Reality Module wizard for chains other than Goerli and Mainnet

- packages/app/src/components/Dropdown.tsx
- packages/app/src/components/input/TimeSelect.tsx
- packages/app/src/utils/oracleValidations.ts
- packages/app/src/views/AddModule/wizards/RealityModule/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Monitoring/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Oracle/components/OracleAlert/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Oracle/components/OracleDelay/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Oracle/components/OracleDelayValidation/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Oracle/components/OracleTemplate/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Oracle/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Proposal/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Review/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/utils/oracleValidations.ts
> [Reality Modules] Encourage the user to set safe values

- packages/app/src/views/AddModule/wizards/RealityModule/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Review/components/SubmittingStatus/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Review/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/service/setupService.ts
closed #128 
This PR contains the UI improvements to show the user the transaction status in the Review section.
> [Reality Module] Informe the user status after clicking submit

- packages/app/src/views/AddModule/wizards/RealityModule/service/setupService.ts
- packages/app/src/views/AddModule/wizards/RealityModule/service/snapshot-space-pinning.ts
- packages/backend/.env.sample
- packages/backend/api/ipfs-pinning/snapshot-settings.ts
- packages/backend/lib/snapshot.ts
Fix to make the backend handle both goerli and mainnet in prod.
> [Reality Module]Fix to make the backend handle both goerli and mainnet in prod

- packages/app/src/components/MultiSelect.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Monitoring/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Proposal/index.tsx
> [Reality Module] Reality Module Wizard UX Improvements

- packages/app/src/views/AddModule/wizards/RealityModule/service/monitoring.ts
- packages/app/src/views/AddModule/wizards/RealityModule/service/setupService.ts
- packages/backend/api/monitoring/notification.ts
- packages/backend/lib/defender/autotasks/on_new_question_from_module.js
- packages/backend/lib/defender/index.ts
- packages/backend/lib/types.ts
- packages/backend/lib/util.ts
- packages/backend/package.json
- packages/backend/yarn.lock
> [Reality Module] Add monitoring for answers submitted for a proposal question at Reality.eth

- packages/app/src/utils/explorers.ts
- packages/app/src/utils/networks.ts
> Add Optimism and Arbitrum networks to the app

- packages/app/src/views/AddModule/wizards/OzGovernor/index.tsx
- packages/app/src/views/AddModule/wizards/OzGovernor/sections/Review/index.tsx
- packages/app/src/views/AddModule/wizards/OzGovernor/sections/Token/index.tsx
Does this PR contain the following tasks:
> Oz governor Review section

- packages/app/package.json
- packages/app/src/views/AddModule/wizards/OzGovernor/index.tsx
- packages/app/src/views/AddModule/wizards/OzGovernor/sections/Governor/index.tsx
- packages/app/src/views/AddModule/wizards/OzGovernor/sections/Review/index.tsx
- packages/app/src/views/AddModule/wizards/OzGovernor/sections/Token/index.tsx
- packages/app/yarn.lock
This PR contains the following tasks.
- OZ Governor Section UI
- Data persistence of the section
- And show the governor section data in the review section
> Oz Governor section

- packages/app/public/index.html
- packages/app/src/views/AddModule/wizards/OzGovernor/index.tsx
- packages/app/src/views/AddModule/wizards/OzGovernor/sections/Governor/index.tsx
- packages/app/src/views/AddModule/wizards/OzGovernor/sections/Review/index.tsx
- packages/app/src/views/AddModule/wizards/OzGovernor/sections/Token/index.tsx
This PR contains the slice three UI improvements and validations following Figma design https://www.figma.com/file/8Je2UmQHCMsHabwNORHaAs/OZ-Governor?node-id=39%3A2517
> [OZ Governor Module] - Token Section Improvements

- packages/app/src/contracts/OZGovernorModule.json
- packages/app/src/utils/modulesValidation.ts
- packages/app/src/views/AddModule/index.tsx
- packages/app/src/views/AddModule/wizards/OzGovernor/index.tsx
- packages/app/src/views/AddModule/wizards/OzGovernor/sections/Review/index.tsx
- packages/app/src/views/AddModule/wizards/OzGovernor/sections/Token/index.tsx
- packages/app/src/views/AddModule/wizards/OzGovernor/service/moduleDeployment.ts
This PR contains the transaction execution when the users populate all the wizards; after that, we deploy the contract and enable the module.
Note: The Deploy button is just available for goerli; the other networks are disabled. Furthermore, the test I made was checking every flow depending on the selection of token type. E.g., existing token, ERC20, ERC721
Test
https://goerli.etherscan.io/address/0xAE8828b6085378880A610c34eD7Abe09d0617E04
https://goerli.etherscan.io/address/0x014CDDb652268F25911b0916C3DCc71819c5fb4B
https://goerli.etherscan.io/address/0xf8ad80347d81De756dd8386df24b1f5D72B6D5a3
> [OZ Governor] - Deploy and Enable Module

- packages/app/package.json
- packages/app/src/components/ethereum/ParamInput.tsx
- packages/app/src/services/index.ts
- packages/app/src/store/modules/helpers.ts
- packages/app/src/utils/explorers.ts
- packages/app/src/utils/networks.ts
- packages/app/src/views/AddModule/index.tsx
- packages/app/src/views/AddModule/wizards/OzGovernor/sections/Review/index.tsx
- packages/app/yarn.lock
This PR:
- updates to the latest Zodiac version
- enables OZ Governor mod on all networks
- adds avalanche support
> Update to latest Zodiac version

- packages/app/src/components/input/ArbitratorSelect.tsx
- packages/app/src/services/index.ts
This PR add Kleros support to the Reality wizard for GC and Gnosis Chain
> add kleros to gc and polygon

- packages/app/src/views/AddModule/wizards/RealityModule/sections/Oracle/index.tsx
This PR corrects an incorrect link.
> fix escalation game link

- packages/app/src/contracts/Tellor.json
- packages/app/src/services/index.ts
- packages/app/src/store/modules/models.ts
- packages/app/src/views/AddModule/wizards/TellorModule/TellorModuleModal.tsx
Added ability for TellorModule owner to invalidate proposal. 
Added `owner` argument to constructor of TellorModule contract, and new argument in modal.
> update tellor interface

- packages/app/src/contracts/Tellor.json
When Tellor module was added - the error of the incompatible object occured. It seems Tellor ABI was imported in a different format. 
[vercel log](https://vercel.com/gnosis-guild/zodiac-safe-app-ui/6imus9DCWWg4wGjfbA8MmVmjpssh)
Compiled Tellor contract and added it in **hh-sol-artifact-1** format to have both **abi** and **bytecode** properties. Bytecode seems to match the ones deployed in mainnet and goerli.
> Fix build error

- packages/app/package.json
- packages/app/yarn.lock
This PR updates the address of the Delay module mastercopy
> update delay mastercopy
