- src/components/input/TimeSelect.tsx
Small style adjustment to make the time unit select not take up too much space on a wide container.
> Updates the timeselect style

- src/views/Panel/Items/DelayModuleItem.tsx
I could be mistaken, but I think the badge should use the `cooldown` value rather than the `expiration` value
> Switches to use cooldown for badge label

- src/views/AddModule/modals/AddModuleModal.tsx
- src/views/TransactionBuilder/TransactionBuilder.tsx
The blur animation was not functioning correctly, resulting in no background blur on the modal overlay which made for some difficult legibility.
Instead of debugging and fixing the animation bug, I've just removed the blur animation all together. This will be more resilient, but also - there is actually [no way of performantly animating a blur effect](https://developers.google.com/web/updates/2017/10/animated-blur).
The modal animation is currently very quick, so the animation isn't really necessary anyways, however, if we do extend the duration, the fading opacity of the background actually gives the illusion of a blur animation anyways.
> Removes modal overlay blur animation and keyframes

- src/utils/explorers.ts
The old RPC endpoint seems to be no longer available.
Could be related to a problem reported on Discord: https://discord.com/channels/881881751369175040/884777203332710460/986620010606780417
> Update Gnosis Chain RPC endpoint

- package.json
- src/views/AddModule/AddModulesView.tsx
- src/views/AddModule/modals/OptimisticGovernorModuleModal.tsx
- yarn.lock
Optimistic Governor module did not have a unique Icon.
A unique icon for the Optimistic Governor module was added in [v0.1.3 of `zodiac-ui-components`](https://github.com/gnosis/zodiac-ui-components/releases/tag/v0.1.3)
> Update `zodiac-ui-components` library version to use new icon

- packages/app/src/components/input/CollateralSelect.tsx
- packages/app/src/store/modules/models.ts
- packages/app/src/views/AddModule/index.tsx
- packages/app/src/views/AddModule/wizards/OptimisticGovernorModule/OptimisticGovernorModuleModal.tsx
This PR fixes an issue with the scaling of USDC on Goerli by changing the decimals from 18 to 6.
This PR also updates the naming of the optimistic governor module to avoid confusion with the OZ/Compound Governor.
> [Optimistic-Governor]: Update goerli bond decimals and OG title

- .github/workflows/dev-cd.yaml
- .github/workflows/prod-release-deploy.yaml
Fixes #126
@samepant: I see that the Vercel deployment says the deployment environment is production for updates to master. Is it possible to create a dev environment where it publishes from master and a separate production environment only for new releases?
If we get this updated, then we need to add/update the `REACT_APP_BACKEND_API_URL` variable in the GitHub workflows.
> Update Vercel deployment and environment variable for Github Workflows

- packages/app/src/services/helpers.ts
- packages/app/src/services/index.ts
- packages/app/src/views/AddModule/wizards/CustomModule/CustomModuleModal.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/service/moduleDeployment.ts
- packages/app/src/views/AddModule/wizards/RealityModuleOld/services/moduleDeploymentOld.ts
- packages/app/src/views/AddModule/wizards/RolesModifier/RolesModifierModal.tsx
This PR addresses https://github.com/gnosis/zodiac-safe-app/issues/160
Some additional straightforward simplifications were made on two functions that encode transactions
> Include setMultisend on the setup stack

- packages/app/package.json
Fix: `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory`
> Fix CI build error: JavaScript heap out of memory

- packages/app/src/utils/explorers.ts
This PR removes a redunant instance of NETWORK.GOERLI in explorers.ts
> remove redunant goerli reference

- packages/app/src/views/AddModule/wizards/OzGovernor/service/moduleDeployment.ts
The interface changed a little, should now use `deployAndEnableOzGovernorModule`.
One missing part: the contracts master copy must med deployed and added to the known contracts in the Zodiac repo.
> Most of deploy and enable OZ Governor

- .github/workflows/prod-release-deploy.yaml
- .gitignore
The `BetaHuhn/deploy-to-vercel-action@v1` action package was getting hung during our release deployment action. I believe this is because we don't have a `build` script in our `package.json` (relying instead on vercel to do the building directly). Also it was originally created before vercel had better support for its CLI tool.
I changed the vercel deployment portion of the action to use the CLI directly.
> Use vercel cli to build backend

- packages/app/src/views/AddModule/wizards/OzGovernor/service/tokenValidation.ts
I experimented with adding an alternative check but ended up just removing the check due to complexity when checking for the `delegate` function in cases when the token contract is a proxy.
Also, I don't think the check brings much more value than the checks already in place.
> Remove a too-strict check for validating tokens

- packages/app/src/views/AddModule/wizards/RealityModule/index.tsx
When the Reality Module setup fails because of an error often caused by ad blockers, we ask the user to disable the blocker and try again.
Closes #199
> Add helpful error message regarding ad blockers

- packages/app/src/views/AddModule/wizards/RealityModule/service/monitoring.ts
- packages/app/src/views/AddModule/wizards/RealityModule/service/setupService.ts
Make sure we use the chain names that OZ Defender expects when setting up monitoring
> [Reality Module] Fix: use OZ chain naming when setting up monitoring

- packages/app/src/views/AddModule/wizards/KlerosRealityModule/KlerosRealityModuleModal.tsx
without this and open monitoring on,
from the user's perspective it might look
like the module froze.
also we want to avoid user spamming
clicks on Add Module as it could break
sentinel
Experience around the Add Module button in the Kleros Snapshot Module was bad, because with open monitoring it can take ~30s for it to resolve, and there was no feedback whatsoever. User could spam click "Add Module", which could break things.
None
Check if deploying, disable buttons and show loading icons if so, pretty simple
> fix: loading info for add module

- packages/app/src/views/AddModule/wizards/OptimisticGovernorModule/OptimisticGovernorModuleModal.tsx
oSnap module can be deployed with rules containing arbitrary string for vote quorum. This can cause ambiguity when verifying proposal if the quorum value was not number.
Restricts votingQuorum param to accept only uint256 when deploying new oSnap module.
> feat: restrict osnap quorum to uint256

- packages/backend/api/monitoring/notification.ts
- packages/backend/lib/defender/autotasks/on_new_question_from_module.ts
- packages/backend/lib/defender/index.ts
Reality Module allows anyone to propose a hash authorizing many transactions to be submitted. Other than gas, there is no cost involved with this action.
The module will only accept proposals whose linked reality.eth question is answered as correctly voted in Snapshot. In order to do this, a bond needs to be placed, which will be considered the intended cost to attack the governor.
The way notifications are currently setup, notifications are launched whenever the hash is proposed. This is an action that any actor could do, and do it for free, so it leaves the door for anyone to pollute the notification system.
1. Notification Channels are created, with `notificationChannelIds` returned
2. An "Autotask" is created, whose job is deploying a new Sentinel watching the Reality.eth contract …
> Stop notifying when Proposals are Submitted, only notify when Answers are submitted

- packages/backend/api/monitoring/notification.ts
- packages/backend/lib/defender/index.ts
this PR could be ignored, since the ids of notification channels are generated independently of the name.
only useful for users that are tracking multiple modules.
screenshot of the motivation of this PR, browsing my Open Zeppelin Sentinel account:
> feat: decrease collisions notification channels

- packages/app/src/components/input/ArbitratorSelect.tsx
- packages/app/src/services/index.ts
Kleros will become available in Goerli for testing. Makes the Kleros Snapshot Module display on Goerli, and allows picking Kleros Arbitrator on the regular wizard on Goerli
> feat: add kleros to goerli

- packages/backend/lib/defender/autotasks/on_new_question_from_module.ts
OpenZeppelin Defender complains that the ABI that the Sentinel has received when created by the Autotask is not valid
Turning it into valid JSON seems to solve the issue. That is, double quotes on properties and no trailing commas.
> fix: autotask abi is now valid JSON

- packages/backend/lib/defender/autotasks/on_new_question_from_module.ts
alert threshold means:
"notify when 2 triggers in time window"
not
"notify up to 2 times in time window"
so it's been removed
> fix: remove alert threshold

- packages/app/src/views/AddModule/wizards/KlerosRealityModule/KlerosRealityModuleModal.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Monitoring/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/sections/Review/index.tsx
- packages/app/src/views/AddModule/wizards/RealityModule/service/monitoring.ts
caused failure when setting up notifications,
preventing all notification setup entirely
Tested
Showing a link with `chatId` instead of `chatID`:
https://github.com/OpenZeppelin/defender-client/blob/917eac7a1cff9ddb6c9e64e1d1aa7a4593d53cba/packages/sentinel/src/models/notification.ts#L51
> fix: chatID -> chatId for telegram

- packages/app/package.json
- packages/app/yarn.lock
Must regenrate yarn.lock after zodiac PR is merged, and new version released
> Bump Zodiac

- packages/app/src/services/snapshot.ts
**Bug Report**
Not applicable - Configuration update.
**Implementation**
Updated SNAPSHOT_HUB_GOERLI and SNAPSHOT_SPACE_GOERLI constants to align with Snapshot's new testnet domain changes.
**Additional Context**
Ensures API calls to Snapshot are directed to the correct updated testnet endpoints.
> Update Goerli URLs for Snapshot Hub and Space Constants

- packages/app/src/services/snapshot.ts
- packages/backend/lib/snapshot.ts
The Snapshot Hub has started to return some fields inside of the snapshot space configuration that are not really part of the space configuration. This will remove those extra attributes after retrieving the space configuration. The actual space config should not include them, and it makes the space config validation fail (as it should).
> Fix snapshot space configuration validation 

- packages/app/src/store/modules/helpers.ts
Roles v1 mods were no longer being detected. this fixes it
> fix an issue in mod detection

- packages/app/src/components/input/ArbitratorSelect.tsx
- packages/app/src/services/index.ts
Added the Reality and Kleros addresses on Sepolia
- [Reality: 0xaf33DcB6E8c5c4D9dDF579f53031b514d19449CA](https://sepolia.etherscan.io/address/0xaf33DcB6E8c5c4D9dDF579f53031b514d19449CA#code)
- [Kleros: 0x05b942faecfb3924970e3a28e0f230910cedff45](https://sepolia.etherscan.io/address/0x05b942faecfb3924970e3a28e0f230910cedff45#code)
[RealityETH/reality-eth-monorepo/.../deployments/11155111/ETH/RealityETH-3.0.json](https://github.com/RealityETH/reality-eth-monorepo/blob/main/packages/contracts/chains/deployments/11155111/ETH/RealityETH-3.0.json#L2)
https://github.com/gnosisguild/zodiac-module-reality/pull/80
> Add support for Reality and Kleros on Sepolia

- packages/app/src/components/MultiSelectBlock.tsx
- packages/app/src/components/ethereum/Address.tsx
- packages/app/src/components/ethereum/AddressExplorerButton.tsx
- packages/app/src/components/ethereum/HashInfo.tsx
- packages/app/src/index.tsx
- packages/app/src/services/ens.ts
- packages/app/src/services/index.ts
- packages/app/src/views/AddModule/wizards/OzGovernor/sections/Review/index.tsx
- packages/app/src/views/AddModule/wizards/RolesModifier/RolesV2ModifierModal.tsx
- packages/app/src/views/AddModule/wizards/components/AddModuleModal.tsx
- packages/app/src/views/ModuleDetails/contract/ContractFunctionHeader.tsx
- packages/app/src/views/Panel/item/ModulePendingItem.tsx
- packages/app/src/views/TransactionBuilder/components/TransactionBlockHeaderButtons.tsx
The PR adjusts the Roles v2 mod's setup modal to allow entering multiple multisend addresses. By default it uses the values that the Safe would use for batching transactions:
This ensures that once https://github.com/safe-global/safe-wallet-web/pull/3768 is live, batch transactions executed through the Safe will actually work with a Roles mod that has been setup using the default configuration.
> Adjust default multisend configuration in Roles v2 setup flow

- packages/app/package.json
- packages/app/src/views/AddModule/wizards/OzGovernor/service/tokenValidation.ts
https://discord.com/channels/881881751369175040/1032974561735606322/1268312094386950286
In the `packages/app/src/views/AddModule/wizards/OzGovernor/service/tokenValidation.ts` file, the following changes were made to fix the bug:
1. Replaced `tokenContract.delegates(RANDOM_VALID_ADDRESS)` with `tokenContract.delegates.staticCall(RANDOM_VALID_ADDRESS)`.
2. Removed the lines:
```typescript
// @ts-ignore
tokenContract.functions['delegateBySig'].name
```
3. Added the line:
```typescript
tokenContract.delegateBySig.name
```
These changes ensure the application correctly identifies and calls the `delegateBySig` function on the contract, addressing the issues caused by the proxy contract used by the Arbitrum Foundation.
The error reported was:
```
Error: missing revert data (action="call", …
```
> fix: governor mod token validation

- packages/app/src/views/ModuleDetails/contract/ContractFunctionQueryBlock.tsx
- packages/app/src/views/ModuleDetails/contract/ContractReadFunctionsList.tsx
There's a bug causing the `target` field of any zodiac mod in the "Read contract" tab to display that mod's address rather than the value actually configured on the mod.
The bug was introduced through the ethers v6 upgrade as the ethers `Contract` class now has a built-in `target` property.
This PR fixes it by using the entire function signature, rather than just the name (which would have also failed with overloaded contract functions).
> fix: name clash with ethers built-in

- packages/app/src/services/index.ts
Closes #246.  
This PR updates the Safe transactions API endpoint in `fetchSafeTransactions`. The previously used endpoint `/api/v1/safes/{safeAddress}/transactions` has been deprecated and is no longer available. Attempting to use it results in a 404 error, breaking the Zodiac Safe App functionality.
To ensure compatibility with the Safe Transaction Service, this fix updates the request to use the correct endpoint:  
✅ **New endpoint:** `/api/v1/safes/{safeAddress}/multisig-transactions/`  
This endpoint specifically returns multisig transactions associated with the given Safe address.
- **Issue:** [[#246](https://github.com/gnosisguild/zodiac-safe-app/issues/246)](https://github.com/gnosisguild/zodiac-safe-app/issues/246)  
- **Affected Networks:** Optimism, Ethereum Sepolia Testnet …
> chore: update deprecated transaction endpoint to multisig-transactions
